### ISSUE TITLE
Unimplemented performance indicators

### ISSUE THREAD

**Issue by jeanbaptistepriez** [PredicSis/predicsis-python-sdk#79]
story pivotal : [#121423965](https://www.pivotaltracker.com/story/show/121423965)

**Comment by jeanbaptistepriez** [comment]
branch: fix-ind_perf (6824ba7):
# modification:
 - lift_curve -> cumulative_gain
# new:
 - precision
 - cumulative_precision
 - lift
 - cumulative_lift
 - target_rate

**Comment by jeanbaptistepriez** [comment]
@Cthao is it right in 17d065a ?

**Comment by Cthao** [comment]
yes.
You also need to had the documentation.

**Comment by jeanbaptistepriez** [comment]
done! ;-)
