### ISSUE TITLE
Remove constraints on names for files to export

### ISSUE THREAD

**Issue by mariePredicsis** [PredicSis/predicsis-python-sdk#95]
This issue has links with https://github.com/PredicSis/predicsis-python-sdk/issues/94

In schemaWithModel.upload_files_to_score('...'), we have to name the files after the chosen names during the project creation step.
These constraints should not stay.
There could be a method returning an empty dictionary to the user:

```
>> prj.structure_for_export() ## or schemaWithModel.structure_for_export() 
... {
...  "master": "",
...  "orders": "",
...  "emails":"",
...   "visitedpages":"" 
...}
```
So it would be easy for the user to copy the strucure, fill it with its paths to the files, and give it as a parameter to the upload method:

````
>> my_structure_for_export= 
>> {
>>  "master": "./mypath/myfilemaster",
>>  "orders": "/mypath/myfileorders",
>>  "emails":"/mypath/myfileemails",
>>   "visitedpages":"/mypath/myfilevisitedpages" 
>>}
schemaWithModel.upload_input_to_export('export#12', my_structure_for_export)
```

**Comment by jeanbaptistepriez** [comment]
Do you agree with this new method?
![capture d ecran 2017-03-20 a 14 05 39](https://cloud.githubusercontent.com/assets/17195729/24101000/ce9c2d1e-0d76-11e7-9fd2-29d5bc46a0a0.png)
It is implemented in #100
